# Generated by Django 4.0.3 on 2025-10-08 16:02

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک (Slug)')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات برند')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک (Slug)')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات دسته\u200cبندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('is_suggest', models.BooleanField(default=False, verbose_name='پیشنهاد وضعیت')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '۱ ستاره'), (2, '۲ ستاره'), (3, '۳ ستاره'), (4, '۴ ستاره'), (5, '۵ ستاره')], default=5, verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک (Slug)')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک (Slug)')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اصلی')),
                ('downloadLink', models.URLField(blank=True, null=True, verbose_name='لینک دانلود خارجی (اختیاری)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand', verbose_name='برند')),
                ('categories', models.ManyToManyField(related_name='products', to='product.category', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گالری محصول',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='مقدار')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature', verbose_name='ویژگی')),
                ('filterValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.featurevalue', verbose_name='مقدار برای فیلترینگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_value', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='product.ProductFeature', to='product.feature', verbose_name='ویژگی\u200cها'),
        ),
        migrations.CreateModel(
            name='LikeOrUnlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('like', models.BooleanField(default=False)),
                ('unlike', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='product.comment', verbose_name='نظر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک\u200cها',
            },
        ),
    ]
