# Generated by Django 4.0.3 on 2025-10-10 08:57

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
