# Generated by Django 4.0.3 on 2025-10-12 10:28

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان <title>')),
                ('description', models.TextField(verbose_name='توضیحات (meta description)')),
                ('og_type', models.CharField(default='website', max_length=50, verbose_name='og:type')),
                ('og_site_name', models.CharField(default='سامسونگ مرکزی آذربایجان', max_length=150, verbose_name='og:site_name')),
                ('og_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='og:title')),
                ('og_description', models.TextField(blank=True, null=True, verbose_name='og:description')),
                ('og_image_url', models.URLField(blank=True, null=True, verbose_name='og:image URL')),
                ('og_url', models.URLField(blank=True, null=True, verbose_name='og:url')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50, verbose_name='twitter:card')),
                ('twitter_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='twitter:title')),
                ('twitter_description', models.TextField(blank=True, null=True, verbose_name='twitter:description')),
                ('twitter_image_url', models.URLField(blank=True, null=True, verbose_name='twitter:image URL')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag', to='product.category', verbose_name='دسته\u200cبندی')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tag', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'متاتگ سئو',
                'verbose_name_plural': 'متاتگ\u200cها',
            },
        ),
    ]
