# Generated by Django 4.0.3 on 2025-10-08 16:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copon', models.CharField(max_length=10, unique=True, verbose_name='کد تخفیف')),
                ('startDate', models.DateTimeField(default=datetime.datetime(2025, 10, 8, 16, 2, 6, 216418, tzinfo=utc), verbose_name='تاریخ شروع')),
                ('endDate', models.DateTimeField(default=datetime.datetime(2025, 10, 8, 16, 2, 6, 216418, tzinfo=utc), verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(verbose_name='درصد تخفیف')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن تخفیفات',
            },
        ),
        migrations.CreateModel(
            name='DiscountBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountTitle', models.CharField(max_length=100, verbose_name='وضوع تخفیف')),
                ('startDate', models.DateTimeField(default=datetime.datetime(2025, 10, 8, 16, 2, 6, 216925, tzinfo=utc), verbose_name='تاریخ شروع')),
                ('endDate', models.DateTimeField(default=datetime.datetime(2025, 10, 8, 16, 2, 6, 217027, tzinfo=utc), verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('isActive', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': ' سبد تخفیف ',
                'verbose_name_plural': 'سبد تخفیف ها ',
            },
        ),
        migrations.CreateModel(
            name='DiscountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountBasket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountOfBasket', to='discount.discountbasket', verbose_name='سبد تخفیف')),
            ],
            options={
                'verbose_name': 'جزییات سبد خرید',
                'verbose_name_plural': 'جزییات سبد تخفیف ها',
            },
        ),
    ]
