# Generated by Django 4.0.3 on 2025-10-07 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 20, 26, 43, 292030, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 20, 26, 43, 292030, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 20, 26, 43, 292030, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 20, 26, 43, 292030, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
    ]
