# Generated by Django 4.0.3 on 2025-10-08 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 20, 41, 8, 982312, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 20, 41, 8, 982312, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 20, 41, 8, 982312, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 20, 41, 8, 982312, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
    ]
