# Generated by Django 4.0.3 on 2025-10-13 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0011_alter_copon_enddate_alter_copon_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copon',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 9, 33, 39, 994580, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='copon',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 9, 33, 39, 993789, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 9, 33, 39, 994580, tzinfo=utc), verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 9, 33, 39, 994580, tzinfo=utc), verbose_name='تاریخ شروع'),
        ),
    ]
