# Generated by Django 4.0.3 on 2025-10-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True, verbose_name='عبارت جستجو')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تعداد جستجو')),
                ('last_searched', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین جستجو')),
            ],
            options={
                'verbose_name': 'جستجوی پرتکرار',
                'verbose_name_plural': 'جستجوهای پرتکرار',
                'ordering': ['-count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='عبارت جستجو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ جستجو')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='کلید نشست')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه جستجو',
                'verbose_name_plural': 'تاریخچه جستجوها',
                'ordering': ['-created_at'],
            },
        ),
    ]
