# Generated by Django 4.0.3 on 2025-10-12 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='یک نام توصیفی برای این مجموعه متا تگ', max_length=200, verbose_name='نام متا تگ')),
                ('title', models.CharField(blank=True, help_text='حداکثر ۶۰ کاراکتر - برای SEO', max_length=60, verbose_name='متا تایتل')),
                ('description', models.TextField(blank=True, help_text='حداکثر ۱۶۰ کاراکتر - برای SEO', max_length=160, verbose_name='متا دیسکریپشن')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='نویسنده')),
                ('copyright', models.CharField(blank=True, max_length=100, verbose_name='کپی رایت')),
                ('robots', models.CharField(blank=True, default='index, follow', help_text='مثال: noindex, nofollow', max_length=100, verbose_name='ربات\u200cها')),
                ('og_title', models.CharField(blank=True, help_text='حداکثر ۹۰ کاراکتر - برای شبکه\u200cهای اجتماعی', max_length=90, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='حداکثر ۲۰۰ کاراکتر - برای شبکه\u200cهای اجتماعی', max_length=200, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='تصویر برای نمایش در شبکه\u200cهای اجتماعی', null=True, upload_to='meta/og_images/', verbose_name='OG Image')),
                ('og_type', models.CharField(blank=True, default='website', help_text='مثال: article, website, product', max_length=50, verbose_name='OG Type')),
                ('og_url', models.URLField(blank=True, verbose_name='OG URL')),
                ('twitter_card', models.CharField(blank=True, default='summary_large_image', help_text='summary, summary_large_image, app, player', max_length=50, verbose_name='Twitter Card Type')),
                ('twitter_site', models.CharField(blank=True, help_text='مانند: @username', max_length=100, verbose_name='Twitter Site')),
                ('twitter_creator', models.CharField(blank=True, help_text='مانند: @username', max_length=100, verbose_name='Twitter Creator')),
                ('twitter_title', models.CharField(blank=True, help_text='حداکثر ۷۰ کاراکتر', max_length=70, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='حداکثر ۲۰۰ کاراکتر', max_length=200, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='meta/twitter_images/', verbose_name='Twitter Image')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('content_type', models.CharField(blank=True, default='text/html; charset=utf-8', max_length=50, verbose_name='Content Type')),
                ('viewport', models.CharField(blank=True, default='width=device-width, initial-scale=1.0', max_length=100, verbose_name='Viewport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Tags',
                'verbose_name_plural': 'Meta Tags',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_tags',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post', to='blog.metatags', verbose_name='متا تگ\u200cها'),
        ),
    ]
