# Generated by Django 4.0.3 on 2025-10-06 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('externalId', models.PositiveIntegerField(help_text='شناسه شهر در API خارجی', unique=True, verbose_name='آیدی API')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
                ('center', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرکز استان')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('externalId', models.PositiveIntegerField(help_text='شناسه استان در API خارجی', unique=True, verbose_name='آیدی API')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressDetail', models.TextField(verbose_name='آدرس دقیق')),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.city', verbose_name='شهر')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.state', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس\u200cهای کاربران',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='order.state', verbose_name='استان'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
    ]
