# Generated by Django 4.0.3 on 2025-10-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_city_state_useraddress_city_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='externalId',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='externalId',
            new_name='external_id',
        ),
    ]
