# Generated by Django 4.0.3 on 2025-10-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='addressDetail',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دقیق'),
        ),
    ]
