# Generated by Django 4.0.3 on 2025-10-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_externalid_city_external_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='external_id',
            new_name='externalId',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='external_id',
            new_name='externalId',
        ),
    ]
