# Generated by Django 4.0.3 on 2025-10-03 13:32

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to),
        ),
        migrations.AlterField(
            model_name='slidermain',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
        migrations.AlterField(
            model_name='slidersite',
            name='imageName',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس اسلایدر'),
        ),
    ]
